from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "outputs"

INCIDENT_DATETIME = "INCIDENT_DATETIME"
FIRST_ON_SCENE_DATETIME = "FIRST_ON_SCENE_DATETIME"
TARGET = "Response_Time_Minutes"

REQUIRED_COLUMNS = [
    INCIDENT_DATETIME,
    FIRST_ON_SCENE_DATETIME,
    "BOROUGH",
]

OPTIONAL_FEATURE_COLUMNS = [
    "INCIDENT_DISPATCH_AREA",
]

NUMERIC_FEATURES = [
    "Hour",
    "DayOfWeek",
    "Month",
    "INITIAL_SEVERITY_LEVEL_CODE",
    "FINAL_SEVERITY_LEVEL_CODE",
]

BASE_CATEGORICAL_FEATURES = [
    "BOROUGH",
    "INCIDENT_CLASSIFICATION",
]

CLASSIFICATION_SOURCE_COLUMNS = [
    "INCIDENT_CLASSIFICATION",
    "FINAL_CALL_TYPE",
    "INITIAL_CALL_TYPE",
]

RESPONSE_TIME_MIN = 0
RESPONSE_TIME_MAX = 120
